name: protein-agent
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - biopython==1.86
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - gemmi==0.7.4
      - greenlet==3.3.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - jiter==0.12.0
      - joblib==1.5.3
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.9
      - langchain==1.2.2
      - langchain-classic==1.0.1
      - langchain-community==0.4.1
      - langchain-core==1.2.6
      - langchain-ollama==1.0.1
      - langchain-openai==1.1.7
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.5
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.3.1
      - langsmith==0.6.1
      - loguru==0.7.3
      - marshmallow==3.26.2
      - matplotlib==3.10.8
      - mdtraj==1.11.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - networkx==3.6.1
      - numpy==2.4.0
      - ollama==0.6.1
      - openai==2.14.0
      - orjson==3.11.5
      - ormsgpack==1.12.1
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - propcache==0.4.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - ramachandraw==1.0.1
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.45
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uuid-utils==0.12.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
